### ISSUE TITLE
Improved API for proper server and client ORM configuration.

### ISSUE THREAD

**Issue by marnusw** [marnusw/fluxible-plugin-waterline-models#3]
@ertrzyiks I've gone through the implementation again and plan to change the API in some significant ways in order to allow proper configuration of the ORM for the server and client respectively.

I've updated the documentation in the main README to reflect the coming changes with code examples. I'd love to get your thoughts on this and see if there are other needs still not being met, or if you think the documentation can be improved! (Comments or PRs welcome.)

**Comment by ertrzyiks** [comment]
Hi @marnusw, new API looks great! New config is similar to what i tried to do, but I was limited by plugin initialization. 

It will be possible to pass any valid param in common config? I had hard time to specify migrate: 'safe' option with v0.2.0

**Comment by marnusw** [comment]
Thanks for the feedback. 

Yes, you should be able to specify any options, including migrate. I don't inspect or modify specific options inside the plugin at all, and now there is proper separation between server and client config, so it should all work.

If you encounter any issues let me know so we can figure it out though.
